<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Close_username</name>
   <tag></tag>
   <elementGuidId>c1991f6c-4022-45fc-9cb6-2c3076c07ba4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signin-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signin-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0db11ae6-8966-4285-a55e-190389e9f06f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>84952318-3604-4ee0-a705-6180fe6605a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-field</value>
      <webElementGuid>c7b96a1b-14e7-436c-a18f-5d70e825c9db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signin-email</value>
      <webElementGuid>44747af8-bbc6-426d-9776-1048f6a69085</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>username</value>
      <webElementGuid>c399ce56-8d0e-4bf6-9c4c-00eaf5d43321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Username</value>
      <webElementGuid>37bec6a8-aece-4b22-b9da-0857c3cb5ad6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signin-email&quot;)</value>
      <webElementGuid>6c6f5b0c-bedc-443c-be1a-7a9aad0817b1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signin-email']</value>
      <webElementGuid>6de04130-2126-4cc4-887c-ba07d1c51f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSignin']/div/div/input</value>
      <webElementGuid>16974500-b601-4392-ba0a-afb33ca17e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>b2946432-7138-4265-820a-226835bcd3aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'signin-email' and @name = 'username' and @placeholder = 'Username']</value>
      <webElementGuid>3dde5463-960e-4862-b9fc-f06eed624664</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
