<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Please provide a valid Username_password</name>
   <tag></tag>
   <elementGuidId>9ccee859-cb99-4b75-8ff3-dee81dbe12ac</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signin-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signin-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a0372cac-2981-4150-9570-d9f5109824d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>f6a9058e-be41-4e40-bd51-c7dca9e08e83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control form-field</value>
      <webElementGuid>805a51d0-8762-4ee1-a123-96033a7b2157</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signin-password</value>
      <webElementGuid>4a93efab-6617-4fb5-9e96-23c63f6b4c9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>149b0893-a4f4-44bb-b804-fe2a81540abe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>037af2b6-3ca9-4b2b-8e56-9dea962d963e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signin-password&quot;)</value>
      <webElementGuid>7060e292-df5a-402e-8331-e3ac6bc6b4f3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signin-password']</value>
      <webElementGuid>8d80cab3-8bca-4f35-9798-add59754bbb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='formSignin']/div[2]/div/input</value>
      <webElementGuid>c2a6e91d-679a-4b19-a919-0f7951241380</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/input</value>
      <webElementGuid>c23f36fe-9c31-4d0a-a050-755e21a8a038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 'signin-password' and @name = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>b824494f-55b6-48d1-9798-c12689d7f0c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
