<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LOG IN_email</name>
   <tag></tag>
   <elementGuidId>becd6779-eb32-463c-99cb-3105a570691a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signup_v1-email</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signup_v1-email']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6b31b410-2eea-47e6-a556-f1b39caec841</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>email</value>
      <webElementGuid>0c631154-255c-4ad9-a5c6-7ff8ed36052e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control valid</value>
      <webElementGuid>68812ffc-4d21-400d-92db-bb7dee291320</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signup_v1-email</value>
      <webElementGuid>a247cb21-34be-4920-b246-0fbf0613c9e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>User ID</value>
      <webElementGuid>5e6683d3-7cd6-4950-b978-b10f4dec86ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>813107a2-72cb-44b4-994b-ad44d88620b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation</name>
      <type>Main</type>
      <value>[EMAIL]</value>
      <webElementGuid>44d20b2b-d7ca-4c68-91b7-516534205bae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>b1a677de-5037-4447-81f0-1636607cc1a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bcc7741b-18d1-4ffe-96d7-3fb3279bdbf8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup_v1-email&quot;)</value>
      <webElementGuid>f52bfd31-acee-4356-be0c-2aabaa594777</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signup_v1-email']</value>
      <webElementGuid>905502ad-852c-4b10-808b-0a740bf710ad</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-signin_v1']/div/input</value>
      <webElementGuid>320dd75d-245f-4c78-ae09-654bde6c8b80</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/input</value>
      <webElementGuid>4ec465fc-8605-444b-baf2-2a8f1e7381ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'email' and @id = 'signup_v1-email' and @placeholder = 'User ID' and @type = 'text']</value>
      <webElementGuid>447d59dc-8536-4f0e-8ab7-a0d8dd37c550</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
