<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_LOG IN_password</name>
   <tag></tag>
   <elementGuidId>2c190bb2-6157-4dfb-9529-119d3aa826b0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#signup_v1-password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='signup_v1-password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>c457524c-67a2-415f-97f6-eae7e7a57fba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>signup_v1-password</value>
      <webElementGuid>00cd5605-aee3-4a68-b219-4795d9d50940</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>d866a082-113e-487e-98fb-ec13768a9e05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>bb8ccc81-ba59-4ddf-9489-dbccb2458047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control valid</value>
      <webElementGuid>1afae5ae-2429-4dfb-b6e7-78ed60374646</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Password</value>
      <webElementGuid>1209bdb3-3a7e-4e38-9d09-105448c18aca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation</name>
      <type>Main</type>
      <value>[L>=6]</value>
      <webElementGuid>f786ff8a-3c70-439d-8a90-c7a593df8449</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validation-message</name>
      <type>Main</type>
      <value>$ must be at least 6 characters</value>
      <webElementGuid>e1a915cc-b27e-444a-a217-db6503d6af75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>19591c3d-5464-4a90-82ed-b7be728c10e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>bf305849-30e8-4774-aa57-bb5136ff4518</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;signup_v1-password&quot;)</value>
      <webElementGuid>84dff93e-798f-4a94-97fc-abc7fbef899e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='signup_v1-password']</value>
      <webElementGuid>5bd03a63-a530-4118-b0b5-ed8a93c2091d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='form-signin_v1']/div[2]/input</value>
      <webElementGuid>158773ab-2a97-4d99-a849-1fa8a8a586ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/input</value>
      <webElementGuid>bc76e11d-8e42-4269-a52f-b8c01fa25428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'signup_v1-password' and @type = 'password' and @name = 'password' and @placeholder = 'Password']</value>
      <webElementGuid>75f2b0d9-a117-454d-acaa-0f688bf3c8ae</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
