<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Projects (1)</name>
   <tag></tag>
   <elementGuidId>43a0048f-dcb8-47df-aaff-112d4d0db989</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='lnkYourDesignsList']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#lnkYourDesignsList</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4113dd65-19c1-41b6-8e02-90ebdb48265b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>lnkYourDesignsList</value>
      <webElementGuid>cb6e0e5a-5d0a-46ad-9685-160d8710dc78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>03e743d4-f8d8-4ca5-84ce-e534c89bfa5a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>LoadUsersTemplates();</value>
      <webElementGuid>1035584f-5fcd-49fe-b963-04a3dfd41b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>dontshowloader</value>
      <webElementGuid>386324b4-2944-49c5-a504-72898adbe2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Projects (1)</value>
      <webElementGuid>c8ac3435-d054-4a8a-9192-274fac4f85ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;lnkYourDesignsList&quot;)</value>
      <webElementGuid>38a6e1da-098e-4fdf-bb55-b4e0f3d9ac46</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='lnkYourDesignsList']</value>
      <webElementGuid>599fa2ea-1a11-4764-a8e6-f254c37900c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//header[@id='header']/div/div/div/div/a[3]</value>
      <webElementGuid>3d700218-192c-4193-b2ad-ec1c8b03ff89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Projects (1)')]</value>
      <webElementGuid>dc5f50ac-baba-49bb-a66b-e8c374b44206</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Prime (20)'])[1]/following::a[1]</value>
      <webElementGuid>0c5dbb6b-6775-4cac-b4b7-b1f539b59552</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='eCovers'])[1]/following::a[2]</value>
      <webElementGuid>ab625314-b187-47da-820b-bed111c7c8f9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bonus (5)'])[1]/preceding::a[1]</value>
      <webElementGuid>e87788f4-8cf3-4d46-8e9e-da065fd89a22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Projects'])[1]/preceding::a[2]</value>
      <webElementGuid>9d297c16-bf7b-404c-851b-2aaa44c4e4a0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Projects (1)']/parent::*</value>
      <webElementGuid>6ff7eda9-fc1e-4c64-891a-fb2ac7fa23d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'javascript:void(0);')])[27]</value>
      <webElementGuid>d4f9c02c-971c-454c-b5f9-26a3cea221ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]</value>
      <webElementGuid>9bc7b399-4097-4185-9135-d261a31d683a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'lnkYourDesignsList' and @href = 'javascript:void(0);' and (text() = 'Projects (1)' or . = 'Projects (1)')]</value>
      <webElementGuid>73484850-b1e5-4488-9fa2-c01717a6a427</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
