<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>95850b5c-b89e-4b0f-bcb1-d4ad6a987557</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//img[contains(@src,&quot;copy-icon&quot;)]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Clone&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>1faa522b-1347-47a1-b127-34015a73ce29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Images/SiteImages/copy-icon.svg</value>
      <webElementGuid>780c4d81-aee3-4098-ab93-a59dba01fa5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Clone</value>
      <webElementGuid>64dd6e2d-4175-4a6f-9654-c9c0a970ac00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;rowUserLiting&quot;)/div[@class=&quot;col-md-3 col-20&quot;]/div[@class=&quot;ecover-box ecover-user-box&quot;]/div[@class=&quot;ecover-options&quot;]/ul[1]/li[4]/a[@class=&quot;dontshowloader&quot;]/img[1]</value>
      <webElementGuid>5df80579-10ee-4dc6-8d7d-aa7e80cb7a5b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='rowUserLiting']/div/div/div[2]/ul/li[4]/a/img</value>
      <webElementGuid>071f7df2-b1ca-4007-9074-f5392de40665</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Clone']</value>
      <webElementGuid>99d61165-975f-476a-ad3e-c0e7ff2194a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/a/img</value>
      <webElementGuid>e3a7d759-e777-4c04-8842-97122fac53cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../Images/SiteImages/copy-icon.svg' and @alt = 'Clone']</value>
      <webElementGuid>4ec9f214-4aa2-44f7-a7f9-8c36308cc5d8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
