<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>02d58820-be8b-4605-9938-96b366c83c95</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//img[@alt='Close Icon'])[2]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>0d9e1512-bd01-4a5c-835b-09b93bb268ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../Images/EditorIcons/close-icon-hover.png</value>
      <webElementGuid>ff853e8b-e4c3-4323-b50c-a87d3b405682</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Close Icon</value>
      <webElementGuid>9076950a-7585-47e7-95f7-cfbd872cf2af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js flexbox flexboxlegacy canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers no-applicationcache svg inlinesvg smil svgclippaths fontawesome-i2svg-active fontawesome-i2svg-complete&quot;]/body[1]/div[@class=&quot;ec-editor-mian-wrappar&quot;]/div[@class=&quot;main-top-bar&quot;]/div[@class=&quot;container-fluid&quot;]/div[@class=&quot;row align-items-center&quot;]/div[@class=&quot;col-md-6&quot;]/div[@class=&quot;main-top-bar-right-side d-flex align-items-center justify-content-end&quot;]/button[@class=&quot;btn btn-primary active tooltip-primary&quot;]/img[2]</value>
      <webElementGuid>b9ea061a-7d33-4ae1-9d18-edcc13b295b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>(//img[@alt='Close Icon'])[2]</value>
      <webElementGuid>2eee2117-076e-4ba7-a406-c8b3bbdfe099</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]/img[2]</value>
      <webElementGuid>4ef58dac-365a-46e7-87e3-20968b4694b6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../Images/EditorIcons/close-icon-hover.png' and @alt = 'Close Icon']</value>
      <webElementGuid>1f444cf4-f839-40e1-b3de-be0efddfed15</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
