<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>3d8cf777-69e2-493f-986f-90377dc6af19</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;WarriorPlus&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='WarriorPlus']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>7b50ed80-e132-4f13-90e2-97458054106f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://members.profitstudio.com/assets/images/worriorplus1.png</value>
      <webElementGuid>32b4708f-88f4-46f0-9e04-daf2a4fbea9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>WarriorPlus</value>
      <webElementGuid>785cf838-3869-48f7-bd28-b351ca98e230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;mainWrapper&quot;]/div[@class=&quot;body_container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5 col-md-12 text-right&quot;]/div[@class=&quot;products-filter-btns-section&quot;]/a[@class=&quot;btn btn-flip-action btn-filter-action btn-flip-clickbank  default-btn mb-3 warriorplus&quot;]/img[1]</value>
      <webElementGuid>6026c93c-2294-4384-8399-184b2fa2ce64</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='WarriorPlus']</value>
      <webElementGuid>e58834c6-bc43-4b4a-9272-4b466a6f9425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[3]/img</value>
      <webElementGuid>be1d7300-24ca-4c33-92de-bcb04527193b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://members.profitstudio.com/assets/images/worriorplus1.png' and @alt = 'WarriorPlus']</value>
      <webElementGuid>816e4676-0be5-4fe2-af9e-1bec5d28c568</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
