<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Videos_btn btn-flip-action btn-filter-act_113b77</name>
   <tag></tag>
   <elementGuidId>2689fb05-ed40-4fa0-a01f-a8b6e00f86d4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(//a[@onclick='ShowStickyPopup();'])[5]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.btn.btn-flip-action.btn-filter-action.btn-flip-clickbank.default-btn.mb-3.mr-2</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>4d2c0eac-2892-420c-9954-12ce97be1ea8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://members.profitstudio.com/top/sellers</value>
      <webElementGuid>40b0266f-2fdc-47f2-9809-f96af28f35d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn btn-flip-action btn-filter-action btn-flip-clickbank  default-btn mb-3 mr-2</value>
      <webElementGuid>e4d3e101-bc5d-4efc-97bc-39b2eda4aadb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>ShowStickyPopup();</value>
      <webElementGuid>45d1339c-0d1c-411d-9c61-1121b2f3f09a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;mainWrapper&quot;]/div[@class=&quot;body_container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5 col-md-12 text-right&quot;]/div[@class=&quot;products-filter-btns-section&quot;]/a[@class=&quot;btn btn-flip-action btn-filter-action btn-flip-clickbank  default-btn mb-3 mr-2&quot;]</value>
      <webElementGuid>82cbfcbf-ee1f-4336-90ae-3bff670ea052</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//a[@onclick='ShowStickyPopup();'])[5]</value>
      <webElementGuid>f012c450-e84c-43d3-af8a-b894903d3d36</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Videos'])[1]/following::a[2]</value>
      <webElementGuid>b5e4858b-0d91-4803-a06a-d1c569603f9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Training'])[1]/following::a[3]</value>
      <webElementGuid>a6541c4d-2711-4a9b-ad87-07d15fa856f5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/preceding::a[2]</value>
      <webElementGuid>71519ce8-610c-4f57-a08f-fd61af908bd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Position'])[1]/preceding::a[2]</value>
      <webElementGuid>cb46c824-eef3-4ae1-980f-32debc1aed2f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://members.profitstudio.com/top/sellers')])[3]</value>
      <webElementGuid>ae8ed17d-cf93-4d16-95bd-99a29ec9cab8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>46042be1-e942-41bf-8eac-ce365034bff3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://members.profitstudio.com/top/sellers']</value>
      <webElementGuid>95f3d03b-449e-4ef9-aaaf-b368172432a2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
