<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>e694c039-0e28-49b0-83c3-619c012a6eb0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;ClickBank&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@alt='ClickBank']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>cb9ca436-7049-4d23-8e8c-7b3a84fc1e8f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://members.profitstudio.com/assets/img/clickbank.png</value>
      <webElementGuid>6606d37d-0ff8-4ba6-b294-d5d60f66ef9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>ClickBank</value>
      <webElementGuid>69f8ce11-394d-4bdc-8091-df5db8fcca7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/div[@class=&quot;mainWrapper&quot;]/div[@class=&quot;body_container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-lg-5 col-md-12 text-right&quot;]/div[@class=&quot;products-filter-btns-section&quot;]/a[@class=&quot;btn btn-flip-action btn-filter-action btn-flip-clickbank  default-btn mb-3 mr-2&quot;]/img[1]</value>
      <webElementGuid>e9f6e94d-3f54-4206-9d53-7b6d10834c61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='ClickBank']</value>
      <webElementGuid>3ae19c76-de0e-40af-b6b7-57081f4e37fb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]/img</value>
      <webElementGuid>49008ede-ec17-498d-a841-50b80f62e3ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://members.profitstudio.com/assets/img/clickbank.png' and @alt = 'ClickBank']</value>
      <webElementGuid>4df69383-4d48-4610-aba5-c1dccabd3452</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
