<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_Submit_svg-inline--fa fa-xmark</name>
   <tag></tag>
   <elementGuidId>7b2d88eb-c21f-4b9b-a4da-6a9a704a7393</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id=&quot;WebinarPopUp&quot;]/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.modal-content.products-popup-content > button.close > span > svg.svg-inline--fa.fa-xmark</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>30fb627b-a878-483c-be8a-33c852c8d8e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>svg-inline--fa fa-xmark</value>
      <webElementGuid>f5122b8f-8d99-470a-a665-5a9a89274ff2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f6baf7ff-c1c0-4de3-aaaa-3428d7c8f2bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>63415c82-9b40-4a4f-b872-b8b9d804e97a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-prefix</name>
      <type>Main</type>
      <value>fas</value>
      <webElementGuid>9e0f66b8-5b38-46e3-ae01-749866fd41ec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>xmark</value>
      <webElementGuid>1fec1dbe-c2d9-4e26-a34d-eaaf28b57494</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>ad54d383-a925-4bc1-8c34-22c1528afd42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>e1ed302f-6e04-4b22-96f8-95627136c70c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 320 512</value>
      <webElementGuid>58cd044f-c940-44a5-8a0b-80556bde84b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;products_popup&quot;)/div[@class=&quot;modal-dialog modal-dialog-centered&quot;]/div[@class=&quot;modal-content products-popup-content&quot;]/button[@class=&quot;close&quot;]/span[1]/svg[@class=&quot;svg-inline--fa fa-xmark&quot;]</value>
      <webElementGuid>a4166a2c-59fb-4b04-aab8-06469ef337d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Submit'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>31299fdc-e8d0-469f-b215-ce0325cdf65c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New Email'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>004601b8-72b7-415c-a5bc-ad9797ff50f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hi, Ahmad Tahir'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>61f7ee71-4783-4b8d-b0df-6e9a4d93c5ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('You', &quot;'&quot;, 're missing the best features &amp; templates...')])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>cc6337fc-2a4b-4ffd-aa4f-4feb7119b607</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
